driverClassName=com.mysql.jdbc.Driver
#初始化建立连接个数
initialSize=10
#最小连接池数量
minIdle=10
#最大连接池数量
maxActive=65
#获取连接最大等待时间ms
maxWait=60000
#配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
timeBetweenEvictionRunsMillis=60000
#配置一个连接在池中最小生存的时间，单位是毫秒
minEvictableIdleTimeMillis=300000
#测试连接
validationQuery=SELECT 1 FROM DUAL
#申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
testWhileIdle=true
#获取连接时执行检测，建议关闭，影响性能
testOnBorrow=false
#归还连接时执行检测，建议关闭，影响性能
testOnReturn=false
#是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
poolPreparedStatements=false
#配置扩展插件，常用的插件有=>stat:监控统计 wall:防御sql注入
filters=stat,wall
