#kafka
bootstrap.servers=127.0.0.1:9092
group.id=test_7
#latest
auto.offset.reset=earliest
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="jowto1234";
topic=sys_fort_lock_learn_log
#clickhouse
url=jdbc:clickhouse://127.0.0.1:8123/learn
username=zpgDk5dvDyH03tHkt/x6fg==
password=EDYUXmba7Nw15cT/6WVR46F9vfjlKOm8MSVUW0H6ssM=
#redis
redis.host=127.0.0.1
redis.port=6379
redis.password=123qweasdZXC!@#
redis.node=192.168.123.250:6379,192.168.123.252:6379
#mysql
mysql.host=127.0.0.1
mysql.port=10000
mysql.databaseList=ys_asset
mysql.username=vS7ddLBiwnfvwFkh4gB5aQ==
mysql.password=j81iCB7xO9GE1Nzt4NTC2Q==
mysql.url=jdbc:mysql://192.168.123.250:3306/ys_asset?characterEncoding=UTF-8
mysql.driverClassName=com.mysql.cj.jdbc.Driver
