# 数据库驱动|不填写HikariCp会自动识别
driverClassName=cc.blynk.clickhouse.ClickHouseDriver
# 最大连接数
maximumPoolSize=64
minimumIdle=10
connectionTimeout=30000
idleTimeout=60000
maxLifetime=70000
validationTimeout=3000
